import random
from datetime import datetime, timedelta
import csv

# Lista de bairros de Arujá com CEPs
bairros_aruja = [
    {"cep": "07400015", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400020", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400025", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400030", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400040", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400050", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400370", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400375", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400380", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400385", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400390", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400395", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400400", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400405", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400410", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400420", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400425", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400430", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400440", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400445", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400450", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400455", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400460", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400465", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400470", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400550", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400555", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400560", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400565", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400570", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400575", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400580", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400585", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400590", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400595", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400600", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400605", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400610", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400615", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400630", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400645", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400650", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400655", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400660", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400665", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400675", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400680", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400690", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400700", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400705", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400710", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400715", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400720", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400725", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400735", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400745", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400755", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400765", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400770", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400775", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400780", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400785", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400790", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400795", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400800", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400805", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400810", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400815", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400820", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400825", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400830", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400835", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400840", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400845", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400850", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400855", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400860", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400865", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400870", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400875", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400880", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400885", "bairro": "Arujá Centro Residencial", "cidade": "Arujá"},
    {"cep": "07400959", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400970", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07400971", "bairro": "Centro", "cidade": "Arujá"},
    {"cep": "07400972", "bairro": "Jardim Rincão", "cidade": "Arujá"},
    {"cep": "07403000", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403005", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403010", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403015", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403020", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403025", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403030", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403035", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403040", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403045", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403050", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403055", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403060", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403065", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403070", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403075", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403080", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403085", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403090", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403100", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403105", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403110", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403113", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403115", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07403120", "bairro": "Arujamérica", "cidade": "Arujá"},
    {"cep": "07404020", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404025", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404030", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404035", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404040", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404045", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404050", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404055", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404060", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404065", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404070", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404075", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404080", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404085", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404090", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404095", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404100", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404105", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404110", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404115", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404120", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404125", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404130", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404135", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404140", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404145", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404150", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404155", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404160", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404165", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404170", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404175", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404180", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404185", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404190", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404195", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404200", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404205", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404210", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404215", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07404290", "bairro": "Mirante do Arujá", "cidade": "Arujá"},
    {"cep": "07411350", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411355", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411360", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411365", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411370", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411375", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411380", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411385", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411390", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411395", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411400", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411405", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411410", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411415", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411420", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411425", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411430", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411435", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411440", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07411445", "bairro": "Cidade Nova Arujá", "cidade": "Arujá"},
    {"cep": "07417100", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417105", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417110", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417115", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417120", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417125", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417130", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417135", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417140", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417145", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417150", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417155", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417160", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417165", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417170", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417175", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417180", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417185", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417190", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417195", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417200", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417210", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417215", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417220", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417225", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417230", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417235", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417240", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417245", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417250", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417255", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417260", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417265", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417270", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417275", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417280", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417285", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417290", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417295", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417300", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417305", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417310", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417315", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417320", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417325", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417330", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417335", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417340", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417345", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417350", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417355", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417360", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417365", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417370", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417375", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417380", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417385", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417390", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417395", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417400", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417405", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417410", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417415", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417420", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417425", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417430", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417435", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417440", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417445", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417450", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417455", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417460", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417465", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417470", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417475", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417480", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417485", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417490", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417495", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417500", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417505", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417510", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417515", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417520", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417525", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417530", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417535", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417540", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417545", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417550", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417555", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417560", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417565", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417570", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417575", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417580", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417585", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417590", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417595", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417600", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07417605", "bairro": "Parque Rodrigo Barreto", "cidade": "Arujá"},
    {"cep": "07428070", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428075", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428080", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428085", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428090", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428095", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428100", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428105", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428110", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428115", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428120", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428125", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428130", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428135", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428140", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428145", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428150", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428155", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428160", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428165", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428170", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428175", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428180", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428185", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428190", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428195", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428200", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428205", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428210", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428215", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428220", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428225", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428230", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428235", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428240", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428245", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428250", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428255", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428260", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428265", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428270", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428275", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428280", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428285", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428290", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428295", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428300", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428305", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428310", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428315", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428320", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428325", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07428330", "bairro": "Jardim Fazenda Rincão", "cidade": "Arujá"},
    {"cep": "07429200", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429205", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429210", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429215", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429220", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429225", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429230", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429235", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429240", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429245", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429250", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429255", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429260", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429265", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429270", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429275", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429280", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429285", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429290", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429295", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429300", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429305", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429310", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429315", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429320", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429325", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07429330", "bairro": "Residencial Real Park", "cidade": "Arujá"},
    {"cep": "07431370", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431375", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431380", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431385", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431390", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431395", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431400", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431405", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431410", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431415", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431420", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431425", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431430", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431435", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431440", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431445", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07431450", "bairro": "Jardim Cury", "cidade": "Arujá"},
    {"cep": "07434430", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434435", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434440", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434445", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434450", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434455", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434460", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434465", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434470", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434475", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434480", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434485", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434490", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434495", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434500", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434505", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434510", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434515", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434520", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434525", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434530", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434535", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07434540", "bairro": "Arujázinho IV", "cidade": "Arujá"},
    {"cep": "07435180", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435185", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435190", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435195", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435200", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435205", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435210", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435215", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435220", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435225", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435230", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435235", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435240", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435245", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435250", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435255", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435260", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435265", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435270", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435275", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435290", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435295", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435300", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435305", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435310", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435315", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435320", "bairro": "Arujá Country Club", "cidade": "Arujá"},
    {"cep": "07435440", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435445", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435450", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435455", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435460", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435465", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435470", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435480", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435485", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435500", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435505", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435515", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435520", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435525", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435530", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435535", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435545", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435550", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435555", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435560", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435565", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435570", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435575", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435580", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435585", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435590", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435595", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435600", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435605", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435610", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435615", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435620", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435635", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435640", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435645", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435650", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435655", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435660", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435670", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435675", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435680", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435685", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435695", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435700", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435705", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435715", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435720", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07435725", "bairro": "Arujázinho I, II e III", "cidade": "Arujá"},
    {"cep": "07439000", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439005", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439010", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439015", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439020", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439025", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439030", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439035", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439040", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439045", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439050", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439055", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439060", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439065", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439070", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439080", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439090", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439100", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439110", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439120", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439125", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439130", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
    {"cep": "07439135", "bairro": "Chácaras Copaco", "cidade": "Arujá"},
]

# Lista de cidades de nascimento
cidades_nascimento = [
    "Arujá",
    "Biritiba Mirim",
    "Ferraz de Vasconcelos",
    "Guararema",
    "Guarulhos",
    "Itaquaquecetuba",
    "Mogi das Cruzes",
    "Poá",
    "Salesópolis",
    "Santa Isabel",
    "Suzano",
]

# Lista de tipos sanguíneos
tipos_sanguineos = ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"]


# Função para gerar uma data aleatória entre duas datas
def random_date(start, end):
    delta = end - start
    random_days = random.randint(0, delta.days)
    return start + timedelta(days=random_days)


# Função para gerar uma data de nascimento com base na faixa etária
def gerar_data_nascimento(faixa_etaria):
    hoje = datetime.today()
    if faixa_etaria == "00 a 05":
        return random_date(
            hoje - timedelta(days=5 * 365), hoje - timedelta(days=0 * 365)
        )
    elif faixa_etaria == "06 a 12":
        return random_date(
            hoje - timedelta(days=12 * 365), hoje - timedelta(days=6 * 365)
        )
    elif faixa_etaria == "13 a 18":
        return random_date(
            hoje - timedelta(days=18 * 365), hoje - timedelta(days=13 * 365)
        )
    else:  # 19 a 59
        return random_date(
            hoje - timedelta(days=59 * 365), hoje - timedelta(days=19 * 365)
        )


# Função para gerar um registro
def gerar_registro(
    id_registro, cid, bairro, cep, faixa_etaria, sexo, cidade_nascimento, tipo_sanguineo
):
    # Gerar data de nascimento
    data_nascimento = gerar_data_nascimento(faixa_etaria).strftime("%Y-%m-%d")

    # Gerar data de inclusão entre 01/10/2024 e 05/03/2025
    data_inclusao = random_date(datetime(2024, 10, 1), datetime(2025, 3, 5)).strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    # Gerar data de validade (1 ano após a data de inclusão)
    data_validade = (
        datetime.strptime(data_inclusao, "%Y-%m-%d %H:%M:%S") + timedelta(days=365)
    ).strftime("%Y-%m-%d %H:%M:%S")

    # Retornar registro no formato SQL e CSV
    registro_sql = f"({id_registro}, {cid}, NULL, NULL, NULL, NULL, NULL, '{sexo}', '{tipo_sanguineo}', '{data_nascimento}', NULL, NULL, '{cidade_nascimento}', 'Brasileira', NULL, NULL, NULL, NULL, NULL, '{cep}', NULL, NULL, NULL, '{bairro}', 'Arujá', 'SP', 'QRCODE_ANONIMO', '{data_validade}', '{data_inclusao}')"
    registro_csv = [
        id_registro,
        cid,
        None,
        None,
        None,
        None,
        None,
        sexo,
        tipo_sanguineo,
        data_nascimento,
        None,
        None,
        cidade_nascimento,
        "Brasileira",
        None,
        None,
        None,
        None,
        None,
        cep,
        None,
        None,
        None,
        bairro,
        "Arujá",
        "SP",
        "QRCODE_ANONIMO",
        "2030-12-31",
        data_inclusao,
    ]
    return registro_sql, registro_csv


# Distribuição de faixas etárias
faixas_etarias = {
    "00 a 05": 45,
    "06 a 12": 62,
    "13 a 18": 16,
    "19 a 59": 21,  # Total de 144 registros
}

# Distribuição de sexo (48% masculino)
sexos = ["M"] * 69 + ["F"] * 75  # 48% de 144 é aproximadamente 69
random.shuffle(sexos)  # Embaralhar para distribuição aleatória

# Distribuição desigual de bairros (garantindo que todos os CEPs sejam usados)
bairros_distribuidos = random.choices(bairros_aruja, k=144)

# Gerar registros
registros_sql = []
registros_csv = []
cid = 128
for i in range(1, 145):  # IDs de 1 a 144
    # Selecionar faixa etária
    faixa_etaria = random.choices(
        list(faixas_etarias.keys()), weights=faixas_etarias.values()
    )[0]
    faixas_etarias[faixa_etaria] -= 1  # Reduzir a contagem da faixa etária

    # Selecionar sexo
    sexo = sexos[i - 1]  # Ajuste para índice 0-based

    # Selecionar bairro e CEP
    bairro_info = bairros_distribuidos[i - 1]  # Ajuste para índice 0-based
    bairro = bairro_info["bairro"]
    cep = bairro_info["cep"]

    # Selecionar cidade de nascimento
    cidade_nascimento = random.choice(cidades_nascimento)

    # Selecionar tipo sanguíneo
    tipo_sanguineo = random.choice(tipos_sanguineos)

    # Gerar registro
    registro_sql, registro_csv = gerar_registro(
        i, cid, bairro, cep, faixa_etaria, sexo, cidade_nascimento, tipo_sanguineo
    )
    registros_sql.append(registro_sql)
    registros_csv.append(registro_csv)

# Montar o INSERT IGNORE SQL
insert_sql = f"""
INSERT IGNORE INTO Carteirinha_tratada (
    ID, CID, Nome, CPF, RG, RG_Orgao_Expeditor, RG_Data_Expeditor, Sexo, Tipo_Sanguineo, Dt_Nascimento,
    Celular, Email, Naturalidade, Nacionalidade, Nome_Pai, Nome_Mae, Nome_Responsavel, Telefone_Responsavel,
    Email_Responsavel, CEP, Endereco, Numero, Complemento, Bairro, Cidade, UF, QRCode, Dt_Validade, Dt_Inclusao
) VALUES
{",\n".join(registros_sql)};
"""

# Salvar o SQL em um arquivo
with open("insert_carteirinha.sql", "w", encoding="utf-8") as file:
    file.write(insert_sql)

# Salvar o CSV em um arquivo
cabecalho_csv = [
    "ID",
    "CID",
    "Nome",
    "CPF",
    "RG",
    "RG_Orgao_Expeditor",
    "RG_Data_Expeditor",
    "Sexo",
    "Tipo_Sanguineo",
    "Dt_Nascimento",
    "Celular",
    "Email",
    "Naturalidade",
    "Nacionalidade",
    "Nome_Pai",
    "Nome_Mae",
    "Nome_Responsavel",
    "Telefone_Responsavel",
    "Email_Responsavel",
    "CEP",
    "Endereco",
    "Numero",
    "Complemento",
    "Bairro",
    "Cidade",
    "UF",
    "QRCode",
    "Dt_Validade",
    "Dt_Inclusao",
]
with open("carteirinha.csv", "w", encoding="utf-8", newline="") as file:
    writer = csv.writer(file, delimiter=";")
    writer.writerow(cabecalho_csv)  # Escrever o cabeçalho
    writer.writerows(registros_csv)  # Escrever os registros

print("Arquivos gerados com sucesso!")
print("- SQL: 'insert_carteirinha.sql'")
print("- CSV: 'carteirinha.csv'")
